#!/usr/bin/env python3
"""Pack picker: edit policy/controls.json, emit policy/pack.cedar, add stdio MCP.

Pack author: add credential/write globs without touching Cedar.
Adapter author: add named shell commands and stdio MCP servers without editing
classify.py regexes.

    python3 policy/pack.py pick          # interactive
    python3 policy/pack.py list
    python3 policy/pack.py add-credential --glob '*/.npmrc' --note 'npm token'
    python3 policy/pack.py add-write --glob '*/infra/prod/*'
    python3 policy/pack.py add-shell --command scp --tool file_exfil
    python3 policy/pack.py add-mcp github -- npx -y @modelcontextprotocol/server-github
    python3 policy/pack.py generate      # write pack.cedar
    python3 policy/pack.py check         # cedar matches controls.json
    python3 policy/pack.py publish       # POST current pack (GURDY_ADMIN_TOKEN)
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import urllib.error
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "adapters" / "cursor" / "hooks"))

from controls import (  # noqa: E402
    CONTROLS_PATH,
    load,
    save,
)

CEDAR_PATH = ROOT / "policy" / "pack.cedar"
SERVERS_PATH = ROOT / "adapters" / "cursor" / "servers.json"

HEADER = """\
// GENERATED from policy/controls.json by `python3 policy/pack.py generate`.
// Do not edit this file. Add globs and tools with `python3 policy/pack.py pick`.
//
// Host-native Read/Write/Shell are not MCP. adapters/cursor/hooks/classify.py
// rewrites them as mcp/tools_call with resource_path / tool / url, then
// gurdy-proxy decides. Do not add a second copy of these forbids for a
// made-up action name — one pack, two transports.
//
// Three fields, never collapsed (§4.2):
//   decision       — what the policy concluded
//   action_applied — forwarded in shadow; blocked when -enforce is on
//   policy_mode    — monitor, or enforce with -enforce
//
// llm/completion does not fire on Cursor Composer. Do not synthesize that
// action from a prompt hook.
//
// Cedar's default is deny, so a permit-all sits underneath the forbids.

"""


def _q(s: str) -> str:
    if '"' in s or "\n" in s:
        raise SystemExit(f"illegal control string (quote/newline): {s!r}")
    return f'"{s}"'


def _like_or_eq(entries: list[dict], attr: str) -> str:
    parts: list[str] = []
    for e in entries:
        value = e.get("value") or ""
        if not value:
            continue
        if e.get("op") == "eq":
            parts.append(f"context.{attr} == {_q(value)}")
        else:
            parts.append(f"context.{attr} like {_q(value)}")
    if not parts:
        return "false"
    if len(parts) == 1:
        return parts[0]
    return "(\n     " + " ||\n     ".join(parts) + "\n    )"


def _path_likes(globs: list[str]) -> str:
    parts = [f"context.resource_path like {_q(g)}" for g in globs]
    if not parts:
        return "false"
    if len(parts) == 1:
        return parts[0]
    return "(\n     " + " ||\n     ".join(parts) + "\n    )"


def render_cedar(doc: dict) -> str:
    ids = doc.get("ids") or {}
    cred_id = ids.get("credential_read", "shadow-credential-read")
    write_id = ids.get("sensitive_write", "shadow-sensitive-write")
    dest_id = ids.get("destructive_fs", "shadow-destructive-fs")
    named_id = ids.get("named_tools", "shadow-named-tools")
    model_id = ids.get("unlisted_model_host", "shadow-unlisted-model-host")

    cred_globs = [e["glob"] for e in doc.get("credential_paths") or [] if e.get("glob")]
    write_globs = [e["glob"] for e in doc.get("write_paths") or [] if e.get("glob")]
    destructive = list(doc.get("destructive_tools") or [])
    named: list[str] = []
    seen: set[str] = set()
    for alias in doc.get("shell_aliases") or []:
        if not alias.get("forbid"):
            continue
        tool = str(alias.get("tool") or "").strip().lower()
        if tool and tool not in seen:
            seen.add(tool)
            named.append(tool)

    out: list[str] = [HEADER]
    out.append('@id("allow-all-monitor")')
    out.append("permit (principal, action, resource);")
    out.append("")

    out.append(f"@id({_q(cred_id)})")
    out.append('@enforce_action("block")')
    out.append('@on_error("open")')
    out.append("forbid (")
    out.append("    principal,")
    out.append('    action == Action::"mcp/tools_call",')
    out.append("    resource")
    out.append(") when {")
    out.append("    context has resource_path &&")
    out.append(f"    {_path_likes(cred_globs)}")
    out.append("};")
    out.append("")

    if write_globs:
        out.append(f"@id({_q(write_id)})")
        out.append('@enforce_action("block")')
        out.append('@on_error("open")')
        out.append("forbid (")
        out.append("    principal,")
        out.append('    action == Action::"mcp/tools_call",')
        out.append("    resource")
        out.append(") when {")
        out.append("    context has tool && context.tool == \"write_file\" &&")
        out.append("    context has resource_path &&")
        out.append(f"    {_path_likes(write_globs)}")
        out.append("};")
        out.append("")

    out.append("// Name-prefix / exact match over the lowercased tool name")
    out.append("// (context.tool is normalized by the engine).")
    out.append(f"@id({_q(dest_id)})")
    out.append('@enforce_action("block")')
    out.append('@on_error("open")')
    out.append("forbid (")
    out.append("    principal,")
    out.append('    action == Action::"mcp/tools_call",')
    out.append("    resource")
    out.append(") when {")
    out.append("    context has tool &&")
    out.append(f"    {_like_or_eq(destructive, 'tool')}")
    out.append("};")
    out.append("")

    if named:
        eqs = " || ".join(f"context.tool == {_q(n)}" for n in named)
        out.append("// Named shell aliases from controls.json (curl/wget/nc → tool).")
        out.append(f"@id({_q(named_id)})")
        out.append('@enforce_action("block")')
        out.append('@on_error("open")')
        out.append("forbid (")
        out.append("    principal,")
        out.append('    action == Action::"mcp/tools_call",')
        out.append("    resource")
        out.append(") when {")
        out.append("    context has tool &&")
        out.append(f"    ({eqs})")
        out.append("};")
        out.append("")

    if doc.get("unlisted_model_host"):
        out.append("// Model HTTP only. Composer never hits gurdy-proxy.")
        out.append("// Loopback is classified \"local\" in this Gurdy pin.")
        out.append(f"@id({_q(model_id)})")
        out.append('@enforce_action("block")')
        out.append('@on_error("open")')
        out.append("forbid (")
        out.append("    principal,")
        out.append('    action == Action::"llm/completion",')
        out.append("    resource")
        out.append(") when {")
        out.append('    context has provider && context.provider == "unlisted"')
        out.append("};")
        out.append("")

    return "\n".join(out)


def generate() -> None:
    text = render_cedar(load())
    CEDAR_PATH.write_text(text, encoding="utf-8")
    print(f"wrote {CEDAR_PATH}")


def check() -> int:
    want = render_cedar(load())
    got = CEDAR_PATH.read_text(encoding="utf-8")
    if got != want:
        print("policy/pack.cedar is stale. Run: python3 policy/pack.py generate", file=sys.stderr)
        return 1
    print("ok: pack.cedar matches controls.json")
    return 0


def cmd_publish(args: argparse.Namespace) -> int:
    if check() != 0:
        return 1
    url = (args.url or os.environ.get("GURDY_DASHBOARD_URL") or "").rstrip("/")
    token = args.token or os.environ.get("GURDY_ADMIN_TOKEN") or ""
    if not url or not token:
        print("mint a policy token on /policy, then:", file=sys.stderr)
        print(
            "  GURDY_DASHBOARD_URL=${GURDY_DASHBOARD_URL} GURDY_ADMIN_TOKEN=gra_… \\",
            file=sys.stderr,
        )
        print("    python3 policy/pack.py publish", file=sys.stderr)
        print("or paste policy/pack.cedar on /policy", file=sys.stderr)
        return 2
    body = json.dumps(
        {
            "cedar": CEDAR_PATH.read_text(encoding="utf-8"),
            "note": args.note or "pack.py publish",
            "name": getattr(args, "name", None) or "local",
            "make_default": bool(getattr(args, "make_default", False)),
        }
    ).encode("utf-8")
    req = urllib.request.Request(
        url + "/api/policy",
        data=body,
        method="POST",
        headers={
            "Authorization": f"Bearer {token}",
            "Accept": "application/json",
            "Content-Type": "application/json",
        },
    )
    try:
        with urllib.request.urlopen(req, timeout=60) as resp:
            payload = json.loads(resp.read() or b"{}")
    except urllib.error.HTTPError as exc:
        detail = exc.read().decode("utf-8", errors="replace")
        print(f"publish failed ({exc.code}): {detail}", file=sys.stderr)
        return 1
    print(f"pack {payload.get('name')} is {payload.get('bundle_ver')} default={payload.get('is_default')}")
    return 0


def cmd_list(_: argparse.Namespace) -> int:
    doc = load()
    print(f"controls: {CONTROLS_PATH}")
    print("\ncredential paths (any tools/call):")
    for e in doc.get("credential_paths") or []:
        print(f"  {e.get('glob'):<22} {e.get('note') or ''}")
    print("\nwrite paths (write_file only):")
    writes = doc.get("write_paths") or []
    if not writes:
        print("  (none — add with: pack.py add-write --glob '*/infra/prod/*')")
    for e in writes:
        print(f"  {e.get('glob'):<22} {e.get('note') or ''}")
    print("\ndestructive tools:")
    for e in doc.get("destructive_tools") or []:
        shell = " shell" if e.get("shell") else ""
        print(f"  {e.get('op')} {e.get('value')}{shell}")
    print("\nshell aliases (classify → Cedar tool name):")
    for e in doc.get("shell_aliases") or []:
        flag = " FORBID" if e.get("forbid") else ""
        print(f"  {e.get('command'):<8} → {e.get('tool')}{flag}  {e.get('note') or ''}")
    servers = json.loads(SERVERS_PATH.read_text(encoding="utf-8")).get("servers") or {}
    print("\nMCP servers (adapters/cursor/servers.json):")
    for name, spec in servers.items():
        wrap = spec.get("wrap", spec.get("transport") == "stdio")
        print(f"  {name:<16} {spec.get('transport')} wrap={wrap}")
    return 0


def _append_unique(lst: list[dict], key: str, value: str, entry: dict) -> bool:
    for e in lst:
        if e.get(key) == value:
            print(f"already present: {value}")
            return False
    lst.append(entry)
    return True


def _dir_parent(glob: str) -> str | None:
    """`*/.ssh/*` does not match the directory `*/.ssh`. Add both."""
    glob = glob.rstrip("/")
    if glob.endswith("/*") and glob != "/*":
        parent = glob[:-2]
        if parent and parent != "*":
            return parent
    return None


def cmd_add_credential(args: argparse.Namespace) -> int:
    glob = args.glob.strip()
    _q(glob)
    doc = load()
    lst = doc.setdefault("credential_paths", [])
    changed = _append_unique(lst, "glob", glob, {"glob": glob, "note": args.note or ""})
    parent = _dir_parent(glob)
    if parent:
        _q(parent)
        if _append_unique(
            lst,
            "glob",
            parent,
            {"glob": parent, "note": (args.note or glob) + " (directory)"},
        ):
            changed = True
            print(f"also added directory glob {parent}")
    if changed:
        save(doc)
        generate()
        print("added credential path. Gate: make corpus")
        if args.example:
            _write_corpus(
                stem="credential",
                tool="read_file",
                path=args.example,
                policy=(doc.get("ids") or {}).get("credential_read", "shadow-credential-read"),
            )
    return 0


def cmd_add_write(args: argparse.Namespace) -> int:
    glob = args.glob.strip()
    _q(glob)
    doc = load()
    lst = doc.setdefault("write_paths", [])
    if _append_unique(lst, "glob", glob, {"glob": glob, "note": args.note or ""}):
        save(doc)
        generate()
        print("added write path (matches write_file only). Gate: make corpus")
        if args.example:
            _write_corpus(
                stem="write",
                tool="write_file",
                path=args.example,
                policy=(doc.get("ids") or {}).get("sensitive_write", "shadow-sensitive-write"),
            )
    return 0


def cmd_add_shell(args: argparse.Namespace) -> int:
    command = args.command.strip()
    tool = (args.tool or command).strip().lower().replace(" ", "_")
    _q(command)
    _q(tool)
    doc = load()
    lst = doc.setdefault("shell_aliases", [])
    entry = {
        "command": command,
        "tool": tool,
        "forbid": not args.monitor_only,
        "note": args.note or "",
    }
    if _append_unique(lst, "command", command, entry):
        save(doc)
        generate()
        print(f"added shell alias {command} → {tool}. Classify picks this up on the next hook.")
        if not args.monitor_only:
            print("Cedar forbids that tool name (shadow-named-tools).")
    return 0


def cmd_add_mcp(args: argparse.Namespace) -> int:
    name = args.name.strip()
    argv = list(args.argv)
    if not argv:
        raise SystemExit("add-mcp: missing command after --")
    doc = json.loads(SERVERS_PATH.read_text(encoding="utf-8"))
    servers = doc.setdefault("servers", {})
    if name in servers and not args.force:
        raise SystemExit(f"server {name!r} exists (pass --force to replace)")
    servers[name] = {
        "transport": "stdio",
        "command": argv[0],
        "args": argv[1:],
        "wrap": True,
        "note": args.note or "Added via policy/pack.py add-mcp",
    }
    SERVERS_PATH.write_text(json.dumps(doc, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {SERVERS_PATH}")
    print("install into Cursor: make install-cursor")
    print(f"proof: a tools/call in ~/.gurdy/ledger/{name}/")
    return 0


def _write_corpus(stem: str, tool: str, path: str, policy: str) -> None:
    corpus = ROOT / "corpus"
    n = 1 + len(list(corpus.glob("*.json")))
    dest = corpus / f"{n:02d}-{stem}.json"
    dest.write_text(
        json.dumps(
            {
                "name": f"{stem}: {path}",
                "attack": f"{tool} {path}",
                "why": f"Generated by pack.py for {policy}.",
                "kind": "wire",
                "steps": [{"call": {"txn": "none", "tool": tool, "args": {"path": path}}}],
                "expect": {
                    "records": [
                        {
                            "action": "mcp/tools_call",
                            "action_applied": "forwarded",
                            "tool": tool,
                            "decision": "block",
                            "policy": policy,
                            "policy_mode": "monitor",
                        }
                    ],
                    "upstream_calls": 1,
                },
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    print(f"wrote {dest}")


def _prompt(msg: str, default: str = "") -> str:
    hint = f" [{default}]" if default else ""
    try:
        got = input(f"{msg}{hint}: ").strip()
    except EOFError:
        return default
    return got or default


def cmd_pick(_: argparse.Namespace) -> int:
    print("Gurdy pack picker  (controls.json → pack.cedar / servers.json)\n")
    while True:
        print("  1) list")
        print("  2) add credential path glob")
        print("  3) add write-only path glob")
        print("  4) add named shell command (curl, wget, scp, …)")
        print("  5) add stdio MCP server")
        print("  6) generate Cedar now")
        print("  7) quit")
        choice = _prompt("choice", "7")
        if choice in {"7", "q", "quit"}:
            return 0
        if choice == "1":
            cmd_list(argparse.Namespace())
            print()
            continue
        if choice == "2":
            glob = _prompt("Cedar glob (e.g. */.npmrc)")
            if not glob:
                continue
            note = _prompt("note")
            example = _prompt("optional corpus example path (empty skips)")
            cmd_add_credential(
                argparse.Namespace(glob=glob, note=note, example=example or None)
            )
            continue
        if choice == "3":
            glob = _prompt("Cedar glob (e.g. */infra/prod/*)")
            if not glob:
                continue
            note = _prompt("note")
            example = _prompt("optional corpus example path (empty skips)")
            cmd_add_write(
                argparse.Namespace(glob=glob, note=note, example=example or None)
            )
            continue
        if choice == "4":
            command = _prompt("shell command word (curl)")
            if not command:
                continue
            tool = _prompt("Cedar tool name", "http_fetch")
            forbid = _prompt("forbid in Cedar? [Y/n]", "Y")
            note = _prompt("note")
            cmd_add_shell(
                argparse.Namespace(
                    command=command,
                    tool=tool,
                    monitor_only=forbid.lower().startswith("n"),
                    note=note,
                )
            )
            continue
        if choice == "5":
            name = _prompt("server name (github)")
            if not name:
                continue
            line = _prompt("launch command (npx -y @modelcontextprotocol/server-github)")
            if not line:
                continue
            note = _prompt("note")
            cmd_add_mcp(
                argparse.Namespace(
                    name=name, argv=line.split(), note=note, force=False
                )
            )
            continue
        if choice == "6":
            generate()
            continue
        print("unknown choice")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    sub = ap.add_subparsers(dest="cmd")

    p_list = sub.add_parser("list", help="show controls and MCP servers")
    p_list.set_defaults(func=cmd_list)

    p_cred = sub.add_parser("add-credential", help="forbid tools/call on a path glob")
    p_cred.add_argument("--glob", required=True)
    p_cred.add_argument("--note", default="")
    p_cred.add_argument("--example", default=None, help="corpus path example")
    p_cred.set_defaults(func=cmd_add_credential)

    p_write = sub.add_parser("add-write", help="forbid write_file on a path glob")
    p_write.add_argument("--glob", required=True)
    p_write.add_argument("--note", default="")
    p_write.add_argument("--example", default=None)
    p_write.set_defaults(func=cmd_add_write)

    p_shell = sub.add_parser("add-shell", help="map a shell word to a Cedar tool name")
    p_shell.add_argument("--command", required=True)
    p_shell.add_argument("--tool", default="")
    p_shell.add_argument("--monitor-only", action="store_true", help="classify only; no forbid")
    p_shell.add_argument("--note", default="")
    p_shell.set_defaults(func=cmd_add_shell)

    p_mcp = sub.add_parser("add-mcp", help="wrap a stdio MCP server")
    p_mcp.add_argument("name")
    p_mcp.add_argument("--note", default="")
    p_mcp.add_argument("--force", action="store_true")
    p_mcp.add_argument("argv", nargs=argparse.REMAINDER)
    p_mcp.set_defaults(func=cmd_add_mcp)

    p_gen = sub.add_parser("generate", help="write policy/pack.cedar")
    p_gen.set_defaults(func=lambda _: (generate() or 0))

    p_check = sub.add_parser("check", help="fail if pack.cedar is stale")
    p_check.set_defaults(func=lambda _: check())

    p_pub = sub.add_parser("publish", help="POST pack.cedar to the dashboard")
    p_pub.add_argument("--url", default="", help="dashboard origin (or GURDY_DASHBOARD_URL)")
    p_pub.add_argument("--token", default="", help="gra_ bearer (or GURDY_ADMIN_TOKEN)")
    p_pub.add_argument("--note", default="", help="stored on the policy row")
    p_pub.add_argument("--name", default="local", help="catalog name (Fleet assignment)")
    p_pub.add_argument(
        "--default",
        dest="make_default",
        action="store_true",
        help="mark this name as the estate default",
    )
    p_pub.set_defaults(func=cmd_publish)

    p_pick = sub.add_parser("pick", help="interactive menu")
    p_pick.set_defaults(func=cmd_pick)

    args = ap.parse_args()
    if not args.cmd:
        ap.print_help()
        print("\nStart here:  python3 policy/pack.py pick")
        return 0
    if args.cmd == "add-mcp" and args.argv[:1] == ["--"]:
        args.argv = args.argv[1:]
    return int(args.func(args) or 0)


if __name__ == "__main__":
    raise SystemExit(main())
