/** Cedar pack builder. Mirrors policy/pack.py render_cedar so a full
 *  catalog publish hashes the same as `python3 policy/pack.py generate`.
 *  Safe in the browser: no filesystem, no crypto.
 */

export type PathGlob = { glob: string; note: string };
export type DestructiveTool = { op: "eq" | "like"; value: string; shell: boolean };
export type ShellAlias = {
  command: string;
  tool: string;
  forbid: boolean;
  note: string;
};

export type ControlsDoc = {
  version: number;
  ids: {
    credential_read: string;
    sensitive_write: string;
    destructive_fs: string;
    named_tools: string;
    unlisted_model_host: string;
  };
  credential_paths: PathGlob[];
  write_paths: PathGlob[];
  destructive_tools: DestructiveTool[];
  shell_aliases: ShellAlias[];
  unlisted_model_host: boolean;
};

/** Same families as policy/controls.json. The builder checkboxes are this list. */
export const CATALOG: ControlsDoc = {
  version: 1,
  ids: {
    credential_read: "shadow-credential-read",
    sensitive_write: "shadow-sensitive-write",
    destructive_fs: "shadow-destructive-fs",
    named_tools: "shadow-named-tools",
    unlisted_model_host: "shadow-unlisted-model-host",
  },
  credential_paths: [
    { glob: "*/.ssh", note: "OpenSSH directory (Glob/list)" },
    { glob: "*/.ssh/*", note: "OpenSSH keys and config" },
    { glob: "*/.aws", note: "AWS directory (Glob/list)" },
    { glob: "*/.aws/*", note: "AWS credentials" },
    { glob: "*/.gnupg", note: "GnuPG directory (Glob/list)" },
    { glob: "*/.gnupg/*", note: "GnuPG homedir" },
    { glob: "*/.env", note: "dotenv" },
    { glob: "*/.env.*", note: "dotenv variants" },
    { glob: "*/id_rsa", note: "RSA private key filename" },
    { glob: "*/id_ed25519", note: "Ed25519 private key filename" },
    { glob: "*/credentials", note: "generic credentials file" },
  ],
  write_paths: [],
  destructive_tools: [
    { op: "like", value: "delete*", shell: false },
    { op: "like", value: "remove*", shell: false },
    { op: "like", value: "rmdir*", shell: true },
    { op: "like", value: "unlink*", shell: true },
    { op: "eq", value: "rm", shell: true },
    { op: "eq", value: "shred", shell: true },
    { op: "like", value: "truncate*", shell: true },
  ],
  shell_aliases: [
    { command: "curl", tool: "http_fetch", forbid: true, note: "HTTP exfil" },
    { command: "wget", tool: "http_fetch", forbid: true, note: "HTTP exfil" },
    { command: "nc", tool: "http_fetch", forbid: true, note: "netcat" },
    { command: "ncat", tool: "http_fetch", forbid: true, note: "nmap netcat" },
  ],
  unlisted_model_host: true,
};

export const RULE_LABEL: Record<string, string> = {
  "allow-all-monitor": "Permit everything the forbids do not catch",
  "shadow-credential-read": "Reading secrets",
  "shadow-sensitive-write": "Writing sensitive paths",
  "shadow-destructive-fs": "Deletes and rm",
  "shadow-named-tools": "curl, wget, nc",
  "shadow-unlisted-model-host": "Unlisted model host",
};

const HEADER = `// GENERATED from policy/controls.json by \`python3 policy/pack.py generate\`.
// Do not edit this file. Add globs and tools with \`python3 policy/pack.py pick\`.
//
// Cursor's built-in Read/Write/Shell are not MCP. hooks/classify.py rewrites
// them as mcp/tools_call with resource_path / tool / url, then gurdy-proxy
// decides. Do not add a second copy of these forbids for a made-up action
// name — one pack, two transports.
//
// Three fields, never collapsed (§4.2):
//   decision       — what the policy concluded
//   action_applied — forwarded in shadow; blocked when -enforce is on
//   policy_mode    — monitor, or enforce with -enforce
//
// llm/completion does not fire on Cursor Composer. Do not synthesize that
// action from a prompt hook.
//
// Cedar's default is deny, so a permit-all sits underneath the forbids.

`;

export type PackSelection = {
  credentialGlobs: string[];
  writeGlobs: string[];
  destructive: boolean;
  namedTools: boolean;
  unlistedModelHost: boolean;
};

export type PackRule = {
  id: string;
  kind: "permit" | "forbid";
  action: string | null;
  label: string;
  paths: string[];
  tools: string[];
  notes: string[];
};

export type PackSummary = {
  permit: boolean;
  rules: PackRule[];
};

export function quoteCedar(s: string): string {
  if (s.includes('"') || s.includes("\n")) {
    throw new Error(`illegal control string (quote/newline)`);
  }
  return `"${s}"`;
}

export function parseGlob(raw: string): string | null {
  const glob = raw.trim();
  if (!glob || glob.length > 256) {
    return null;
  }
  if (glob.includes('"') || glob.includes("\n")) {
    return null;
  }
  return glob;
}

/** A glob ending in slash-star does not match the directory itself. Add both. */
export function dirParent(glob: string): string | null {
  const trimmed = glob.replace(/\/+$/, "");
  if (trimmed.endsWith("/*") && trimmed !== "/*") {
    const parent = trimmed.slice(0, -2);
    if (parent && parent !== "*") {
      return parent;
    }
  }
  return null;
}

function likeOrEq(entries: DestructiveTool[], attr: string): string {
  const parts: string[] = [];
  for (const e of entries) {
    if (!e.value) {
      continue;
    }
    if (e.op === "eq") {
      parts.push(`context.${attr} == ${quoteCedar(e.value)}`);
    } else {
      parts.push(`context.${attr} like ${quoteCedar(e.value)}`);
    }
  }
  if (parts.length === 0) {
    return "false";
  }
  if (parts.length === 1) {
    return parts[0];
  }
  return "(\n     " + parts.join(" ||\n     ") + "\n    )";
}

function pathLikes(globs: string[]): string {
  const parts = globs.map((g) => `context.resource_path like ${quoteCedar(g)}`);
  if (parts.length === 0) {
    return "false";
  }
  if (parts.length === 1) {
    return parts[0];
  }
  return "(\n     " + parts.join(" ||\n     ") + "\n    )";
}

function forbidBlock(id: string, action: string, whenLines: string[]): string[] {
  return [
    `@id(${quoteCedar(id)})`,
    '@enforce_action("block")',
    '@on_error("open")',
    "forbid (",
    "    principal,",
    `    action == Action::${quoteCedar(action)},`,
    "    resource",
    ") when {",
    ...whenLines.map((line) => `    ${line}`),
    "};",
    "",
  ];
}

export function renderCedar(doc: ControlsDoc): string {
  const ids = doc.ids;
  const credGlobs = (doc.credential_paths ?? []).map((e) => e.glob).filter(Boolean);
  const writeGlobs = (doc.write_paths ?? []).map((e) => e.glob).filter(Boolean);
  const destructive = [...(doc.destructive_tools ?? [])];
  const named: string[] = [];
  const seen = new Set<string>();
  for (const alias of doc.shell_aliases ?? []) {
    if (!alias.forbid) {
      continue;
    }
    const tool = (alias.tool || "").trim().toLowerCase();
    if (tool && !seen.has(tool)) {
      seen.add(tool);
      named.push(tool);
    }
  }

  const out: string[] = [HEADER];
  out.push('@id("allow-all-monitor")');
  out.push("permit (principal, action, resource);");
  out.push("");

  if (credGlobs.length > 0) {
    out.push(
      ...forbidBlock(ids.credential_read, "mcp/tools_call", [
        "context has resource_path &&",
        pathLikes(credGlobs),
      ]),
    );
  }

  if (writeGlobs.length > 0) {
    out.push(
      ...forbidBlock(ids.sensitive_write, "mcp/tools_call", [
        'context has tool && context.tool == "write_file" &&',
        "context has resource_path &&",
        pathLikes(writeGlobs),
      ]),
    );
  }

  if (destructive.length > 0) {
    out.push("// Name-prefix / exact match over the lowercased tool name");
    out.push("// (context.tool is normalized by the engine).");
    out.push(
      ...forbidBlock(ids.destructive_fs, "mcp/tools_call", [
        "context has tool &&",
        likeOrEq(destructive, "tool"),
      ]),
    );
  }

  if (named.length > 0) {
    const eqs = named.map((n) => `context.tool == ${quoteCedar(n)}`).join(" || ");
    out.push("// Named shell aliases from controls.json (curl/wget/nc → tool).");
    out.push(
      ...forbidBlock(ids.named_tools, "mcp/tools_call", [
        "context has tool &&",
        `(${eqs})`,
      ]),
    );
  }

  if (doc.unlisted_model_host) {
    out.push("// Model HTTP only. Composer never hits gurdy-proxy.");
    out.push('// Loopback is classified "local" in this Gurdy pin.');
    out.push(
      ...forbidBlock(ids.unlisted_model_host, "llm/completion", [
        'context has provider && context.provider == "unlisted"',
      ]),
    );
  }

  return out.join("\n");
}

export function defaultSelection(): PackSelection {
  return {
    credentialGlobs: CATALOG.credential_paths.map((e) => e.glob),
    writeGlobs: CATALOG.write_paths.map((e) => e.glob),
    destructive: CATALOG.destructive_tools.length > 0,
    namedTools: CATALOG.shell_aliases.some((a) => a.forbid),
    unlistedModelHost: CATALOG.unlisted_model_host,
  };
}

function noteFor(glob: string, kind: "credential" | "write"): string {
  const list = kind === "credential" ? CATALOG.credential_paths : CATALOG.write_paths;
  return list.find((e) => e.glob === glob)?.note ?? "";
}

export function docFromSelection(sel: PackSelection): ControlsDoc {
  const credOrder = CATALOG.credential_paths.map((e) => e.glob);
  const credSet = new Set(sel.credentialGlobs);
  const credential_paths = [
    ...credOrder.filter((g) => credSet.has(g)),
    ...sel.credentialGlobs.filter((g) => !credOrder.includes(g)),
  ].map((glob) => ({ glob, note: noteFor(glob, "credential") }));

  const writeOrder = CATALOG.write_paths.map((e) => e.glob);
  const writeSet = new Set(sel.writeGlobs);
  const write_paths = [
    ...writeOrder.filter((g) => writeSet.has(g)),
    ...sel.writeGlobs.filter((g) => !writeOrder.includes(g)),
  ].map((glob) => ({ glob, note: noteFor(glob, "write") }));

  return {
    version: 1,
    ids: CATALOG.ids,
    credential_paths,
    write_paths,
    destructive_tools: sel.destructive ? CATALOG.destructive_tools : [],
    shell_aliases: CATALOG.shell_aliases.map((a) => ({
      ...a,
      forbid: sel.namedTools ? a.forbid : false,
    })),
    unlisted_model_host: sel.unlistedModelHost,
  };
}

export function cedarFromSelection(sel: PackSelection): string {
  return renderCedar(docFromSelection(sel));
}

function extractQuoted(body: string, prefix: string): string[] {
  const out: string[] = [];
  const re = new RegExp(
    `${prefix.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\s*(?:==|like)\\s*"([^"]*)"`,
    "g",
  );
  for (const m of body.matchAll(re)) {
    out.push(m[1]);
  }
  return out;
}

export function summarizeCedar(cedar: string): PackSummary {
  const matches = [...cedar.matchAll(/@id\("([^"]+)"\)/g)];
  const rules: PackRule[] = [];
  let permit = false;

  for (let i = 0; i < matches.length; i++) {
    const id = matches[i][1];
    const start = matches[i].index! + matches[i][0].length;
    const end = i + 1 < matches.length ? matches[i + 1].index! : cedar.length;
    const body = cedar.slice(start, end);
    const action = body.match(/Action::"([^"]+)"/)?.[1] ?? null;
    const paths = extractQuoted(body, "context.resource_path");
    const tools = extractQuoted(body, "context.tool");
    const isPermit = /\bpermit\b/.test(body);
    if (isPermit) {
      permit = true;
    }
    const notes: string[] = [];
    if (id === CATALOG.ids.unlisted_model_host) {
      notes.push("Does not fire on Cursor Composer. There is no chokepoint on model HTTP.");
    }
    if (id === CATALOG.ids.named_tools) {
      const cmds = CATALOG.shell_aliases
        .filter((a) => a.forbid)
        .map((a) => a.command);
      if (cmds.length) {
        notes.push(`Classified from ${cmds.join(", ")}.`);
      }
    }
    rules.push({
      id,
      kind: isPermit ? "permit" : "forbid",
      action,
      label: RULE_LABEL[id] ?? id,
      paths,
      tools,
      notes,
    });
  }

  return { permit, rules };
}

export function selectionFromCedar(cedar: string): PackSelection {
  const summary = summarizeCedar(cedar);
  const byId = new Map(summary.rules.map((r) => [r.id, r]));
  const cred = byId.get(CATALOG.ids.credential_read);
  const write = byId.get(CATALOG.ids.sensitive_write);
  return {
    credentialGlobs: cred?.paths ?? [],
    writeGlobs: write?.paths ?? [],
    destructive: byId.has(CATALOG.ids.destructive_fs),
    namedTools: byId.has(CATALOG.ids.named_tools),
    unlistedModelHost: byId.has(CATALOG.ids.unlisted_model_host),
  };
}

export function namedToolLabel(): string {
  const cmds = CATALOG.shell_aliases.filter((a) => a.forbid).map((a) => a.command);
  const tools = [
    ...new Set(CATALOG.shell_aliases.filter((a) => a.forbid).map((a) => a.tool)),
  ];
  return `${cmds.join(", ")} → ${tools.join(", ")}`;
}

export function destructiveLabel(): string {
  return CATALOG.destructive_tools
    .map((t) => (t.op === "eq" ? t.value : t.value))
    .join(", ");
}

export function toggleGlob(current: string[], glob: string, catalogOrder: string[]): string[] {
  const set = new Set(current);
  if (set.has(glob)) {
    set.delete(glob);
  } else {
    set.add(glob);
  }
  const extras = [...set].filter((g) => !catalogOrder.includes(g));
  return [...catalogOrder.filter((g) => set.has(g)), ...extras];
}

export function addGlobs(current: string[], glob: string, withParent: boolean): string[] {
  const parsed = parseGlob(glob);
  if (!parsed) {
    return current;
  }
  const next = [...current];
  const add = (g: string) => {
    if (!next.includes(g)) {
      next.push(g);
    }
  };
  add(parsed);
  if (withParent) {
    const parent = dirParent(parsed);
    if (parent) {
      add(parent);
    }
  }
  return next;
}
